import List from './Lista.js'

let border_list = new List()
border_list.pushDivisa("AC").pushDivisa("AM").pushDivisa("RO")
border_list.push("AL").pushDivisa("SE").pushDivisa("PE").pushDivisa("BA")
border_list.push("AP").pushDivisa("PA")
border_list.push("AM").pushDivisa("AC").pushDivisa("RO").pushDivisa("MT").pushDivisa("PA").pushDivisa("RR")
border_list.push("BA").pushDivisa("ES").pushDivisa("MG").pushDivisa("GO")
           .push("TO").pushDivisa("GO").pushDivisa("PI").pushDivisa("PE").pushDivisa("SE").pushDivisa("GO").pushDivisa("AL")
border_list.push("CE").pushDivisa("PE").pushDivisa("RN").pushDivisa("PA").pushDivisa("PI")
border_list.push("DF").pushDivisa("GO").pushDivisa("MG")
border_list.push("ES").pushDivisa("MG").pushDivisa("RJ").pushDivisa("BA")
border_list.push("GO").pushDivisa("MT").pushDivisa("MS").pushDivisa("BA").pushDivisa("MG").pushDivisa("TO")
border_list.push("MA").pushDivisa("PI").pushDivisa("TO").pushDivisa("PA")
border_list.push("MT").pushDivisa("RO").pushDivisa("AM").pushDivisa("PA").pushDivisa("TO").pushDivisa("GO").pushDivisa("MS")
border_list.push("MS").pushDivisa("MT").pushDivisa("GO").pushDivisa("SP").pushDivisa("PR").pushDivisa("MG")
border_list.push("MG").pushDivisa("SP").pushDivisa("RG").pushDivisa("ES").pushDivisa("BA").pushDivisa("DF").pushDivisa("GO").pushDivisa("MS")
border_list.push("PA").pushDivisa("MA").pushDivisa("TO").pushDivisa("MT").pushDivisa("AM").pushDivisa("RR").pushDivisa("AP")
border_list.push("CE").pushDivisa("PB").pushDivisa("RN").pushDivisa("PI")
border_list.push("PR").pushDivisa("SC").pushDivisa("RS")
border_list.push("PE").pushDivisa("AL").pushDivisa("BA").pushDivisa("PI").pushDivisa("CE").pushDivisa("PB")
border_list.push("RN").pushDivisa("CE").pushDivisa("PB")
border_list.push("RS").pushDivisa("SC")
border_list.push("RO").pushDivisa("MT").pushDivisa("AM").pushDivisa("AC")
border_list.push("RR").pushDivisa("AM")
border_list.push("SC").pushDivisa("PR").pushDivisa("RS")
border_list.push("SP").pushDivisa("PR").pushDivisa("MS").pushDivisa("MG").pushDivisa("RJ")
border_list.push("SE").pushDivisa("BA").pushDivisa("SE")
border_list.push("TO").pushDivisa("PA").pushDivisa("MT").pushDivisa("GO").pushDivisa("BA").pushDivisa("PI").pushDivisa("MA")


console.log(border_list)