import List from './Lista.js'

let border_list = new List()
border_list.push("AC").push("AM").push("RO")
border_list.push("AL").push("SE").push("PE").push("BA")
border_list.push("AP").push("PA")
border_list.push("AM").push("AC").push("RO").push("MT").push("PA").push("RR")
border_list.push("BA").push("ES").push("MG").push("GO")
           .push("TO").push("GO").push("PI").push("PE").push("SE").push("GO").push("AL")
border_list.push("CE").push("PE").push("RN").push("PA").push("PI")
border_list.push("DF").push("GO").push("MG")
border_list.push("ES").push("MG").push("RJ").push("BA")
border_list.push("GO").push("MT").push("MS").push("BA").push("MG").push("TO")
border_list.push("MA").push("PI").push("TO").push("PA")
border_list.push("MT").push("RO").push("AM").push("PA").push("TO").push("GO").push("MS")
border_list.push("MS").push("MT").push("GO").push("SP").push("PR").push("MG")
border_list.push("MG").push("SP").push("RG").push("ES").push("BA").push("DF").push("GO").push("MS")
border_list.push("PA").push("MA").push("TO").push("MT").push("AM").push("RR").push("AP")
border_list.push("CE").push("PB").push("RN").push("PI")
border_list.push("PR").push("SC").push("RS")
border_list.push("PE").push("AL").push("BA").push("PI").push("CE").push("PB")
border_list.push("RN").push("CE").push("PB")
border_list.push("RS").push("SC")
border_list.push("RO").push("MT").push("AM").push("AC")
border_list.push("RR").push("AM")
border_list.push("SC").push("PR").push("RS")
border_list.push("SP").push("PR").push("MS").push("MG").push("RJ")
border_list.push("SE").push("BA").push("SE")
border_list.push("TO").push("PA").push("MT").push("GO").push("BA").push("PI").push("MA")


console.log(border_list)