import List from './Lista.js'

let border_list = new List()
border_list.pushdivisa("AC").pushdivisa("AM").pushdivisa("RO")
border_list.push("AL").pushdivisa("SE").pushdivisa("PE").pushdivisa("BA")
border_list.push("AP").pushdivisa("PA")
border_list.push("AM").pushdivisa("AC").pushdivisa("RO").pushdivisa("MT").pushdivisa("PA").pushdivisa("RR")
border_list.push("BA").pushdivisa("ES").pushdivisa("MG").pushdivisa("GO")
           .push("TO").pushdivisa("GO").pushdivisa("PI").pushdivisa("PE").pushdivisa("SE").pushdivisa("GO").pushdivisa("AL")
border_list.push("CE").pushdivisa("PE").pushdivisa("RN").pushdivisa("PA").pushdivisa("PI")
border_list.push("DF").pushdivisa("GO").pushdivisa("MG")
border_list.push("ES").pushdivisa("MG").pushdivisa("RJ").pushdivisa("BA")
border_list.push("GO").pushdivisa("MT").pushdivisa("MS").pushdivisa("BA").pushdivisa("MG").pushdivisa("TO")
border_list.push("MA").pushdivisa("PI").pushdivisa("TO").pushdivisa("PA")
border_list.push("MT").pushdivisa("RO").pushdivisa("AM").pushdivisa("PA").pushdivisa("TO").pushdivisa("GO").pushdivisa("MS")
border_list.push("MS").pushdivisa("MT").pushdivisa("GO").pushdivisa("SP").pushdivisa("PR").pushdivisa("MG")
border_list.push("MG").pushdivisa("SP").pushdivisa("RG").pushdivisa("ES").pushdivisa("BA").pushdivisa("DF").pushdivisa("GO").pushdivisa("MS")
border_list.push("PA").pushdivisa("MA").pushdivisa("TO").pushdivisa("MT").pushdivisa("AM").pushdivisa("RR").pushdivisa("AP")
border_list.push("CE").pushdivisa("PB").pushdivisa("RN").pushdivisa("PI")
border_list.push("PR").pushdivisa("SC").pushdivisa("RS")
border_list.push("PE").pushdivisa("AL").pushdivisa("BA").pushdivisa("PI").pushdivisa("CE").pushdivisa("PB")
border_list.push("RN").pushdivisa("CE").pushdivisa("PB")
border_list.push("RS").pushdivisa("SC")
border_list.push("RO").pushdivisa("MT").pushdivisa("AM").pushdivisa("AC")
border_list.push("RR").pushdivisa("AM")
border_list.push("SC").pushdivisa("PR").pushdivisa("RS")
border_list.push("SP").pushdivisa("PR").pushdivisa("MS").pushdivisa("MG").pushdivisa("RJ")
border_list.push("SE").pushdivisa("BA").pushdivisa("SE")
border_list.push("TO").pushdivisa("PA").pushdivisa("MT").pushdivisa("GO").pushdivisa("BA").pushdivisa("PI").pushdivisa("MA")


console.log(border_list)